sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 020908
  hwobs:
    bucket-name: sky-takeout
    access-key-id: 9X7XLHP3TUKWU5TOJM2X
    access-key-secret: OxCvdlCj4vwp9mXMdBTqw4ncU7WGUHrra9z1YSzv
    endpoint: obs.cn-north-4.myhuaweicloud.com
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wxc8295b93d6912e18
    secret: 5fd0e544893c4d0a7df38a8bc56d7f32
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://localhost/notify/paySuccess
    refundNotifyUrl: https://58869fb.r2.cpolar.top/notify/refundSuccess