sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 020908
  hwobs:
    bucket-name: sky-takeout
    access-key-id: 9X7XLHP3TUKWU5TOJM2X
    access-key-secret: OxCvdlCj4vwp9mXMdBTqw4ncU7WGUHrra9z1YSzv
    endpoint: obs.cn-north-4.myhuaweicloud.com
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: wxc8295b93d6912e18
    secret: 5fd0e544893c4d0a7df38a8bc56d7f32